import Head from "next/head";
import { Box } from "@chakra-ui/react";
import { Inter } from "next/font/google";
import { Container } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg="tomato" w="100%" p={4} color="white">
        This is the Box
      </Box>
    </>
  );
}
